//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_booking
    {
        public long bookingId { get; set; }
        public Nullable<long> hotelid { get; set; }
        public Nullable<long> roomid { get; set; }
        public string statusOfBooking { get; set; }
        public string bookingDate { get; set; }
        public Nullable<int> isActive { get; set; }
    }
}
