//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hotel
    {
        public long hid { get; set; }
        public string hotelName { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string pincode { get; set; }
        public Nullable<long> contactNumber { get; set; }
        public string contactPerson { get; set; }
        public string website { get; set; }
        public string facebook { get; set; }
        public string Twitter { get; set; }
        public string isActive { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public string updatedBy { get; set; }
    }
}
